<?php

namespace PortalBundle\Repository;

/**
 * CurrentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CurrentBookRepository extends \Doctrine\ORM\EntityRepository
{
}