<?php

namespace PortalBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ReaderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReaderRepository extends EntityRepository
{
	public function getReaderBooks($readerId) {
		$readerBooks = $this->getEntityManager()->createQuery(
			"SELECT 
					r.id,
					b.id AS id, 
					b.title AS title,
					b.imageName AS imageName,					
					a.id AS authorId,					
					a.name AS authorName   
			 FROM PortalBundle:Reader r 
			 JOIN r.books b			 
			 JOIN b.author a
			 WHERE r.id = $readerId			 
			 ORDER BY b.addDate DESC"
		)->getResult();

		return $readerBooks;
	}

	public function getReaderRatings($readerId) {
		$readerRatings = $this->getEntityManager()->createQuery(
			"SELECT 
					r.id,
					b.id AS bookId, 
					b.title AS bookTitle,
					rat.rate AS rate  
			 FROM PortalBundle:Reader r 
			 JOIN r.ratings rat	
			 JOIN rat.book b		 
			 WHERE r.id = $readerId			 
			 ORDER BY rat.id DESC"
		)->getResult();

		return $readerRatings;		
	}

	public function getReaderReviews($readerId) {
		$readerReviews = $this->getEntityManager()->createQuery(
			"SELECT 
					r.id,
					b.id AS bookId, 
					b.title AS bookTitle,
					rev.id AS id,
					rev.publishDate AS publishDate  
			 FROM PortalBundle:Reader r 
			 JOIN r.reviews rev	
			 JOIN rev.book b		 
			 WHERE r.id = $readerId			 
			 ORDER BY publishDate DESC"
		)->getResult();

		return $readerReviews;		
	}


}
