<?php

namespace PortalBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ReviewRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReviewRepository extends EntityRepository
{

	public function getBookReviews($bookId) 
	{
		$bookReviews = $this->getEntityManager()->createQuery(
			"SELECT r
			 FROM PortalBundle:Review r 
			 WHERE r.book = '$bookId'" 
		)->getResult();
		return $bookReviews;
	}

}
