<?php

namespace PortalBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TranslatorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TranslatorRepository extends EntityRepository
{
}
