<?php

namespace PortalBundle\Repository;

/**
 * WantedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WantedBookRepository extends \Doctrine\ORM\EntityRepository
{
}